"use client"

import { useEffect, useRef } from "react"
import type { GlobeInstance } from "globe.gl"
import { feature } from "topojson-client"
import type { Topology, GeometryCollection } from "topojson-specification"
import worldCountries from "world-atlas/countries-110m.json"
import landDots from "@/data/land-dots.json"

interface OfficeMarker {
  id: string
  location: [number, number]
  label: string
}

interface GlobeLiveProps {
  offices?: OfficeMarker[]
  highlightedCountries?: string[]
  countryColor?: string
  baseColor?: string
  className?: string
}

interface DotPoint {
  lat: number
  lng: number
  color: string
  radius: number
}

const defaultOffices: OfficeMarker[] = [
  { id: "castellon", location: [39.9439, -0.0629], label: "IPLA Castellón (Sede Central)" },
  { id: "canarias", location: [28.42, -16.285], label: "IPLA Canarias" },
  { id: "chile", location: [-34.4421, -70.9441], label: "IPLA Chile" },
]

const defaultHighlightedCountries = [
  "United States of America", "Mexico", "Peru", "Chile", "Spain", "Portugal",
  "France", "United Kingdom", "Ireland", "Belgium", "Netherlands", "Germany",
  "Finland", "Turkey", "Australia",
]

const LAND_DOT_RADIUS = 0.16
const OFFICE_DOT_RADIUS = 0.4

const PULSE_STYLE_ID = "ipla-globe-marker-pulse"

function ensurePulseKeyframes() {
  if (document.getElementById(PULSE_STYLE_ID)) return
  const style = document.createElement("style")
  style.id = PULSE_STYLE_ID
  style.textContent = `
    @keyframes ipla-marker-pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.6; }
    }
  `
  document.head.appendChild(style)
}

function buildOfficeBadge(office: OfficeMarker, color: string) {
  ensurePulseKeyframes()
  // three-globe manages position/transform/display on the element it
  // receives directly, so the actual visual styling lives on a child
  // it never touches.
  const wrapper = document.createElement("div")
  wrapper.style.pointerEvents = "none"

  const badge = document.createElement("div")
  badge.style.cssText = `
    transform: translate(-50%, -130%);
    display: flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.15rem 0.35rem;
    background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
    border-radius: 3px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.25);
    white-space: nowrap;
  `
  const dot = document.createElement("span")
  dot.style.cssText = `
    width: 5px;
    height: 5px;
    background: ${color};
    border-radius: 50%;
    box-shadow: 0 0 6px ${color};
    animation: ipla-marker-pulse 1.5s ease-in-out infinite;
    flex-shrink: 0;
  `
  const text = document.createElement("span")
  text.style.cssText = `
    font-family: system-ui, sans-serif;
    font-size: 0.5rem;
    font-weight: 600;
    color: #ffffff;
  `
  text.textContent = office.label
  badge.appendChild(dot)
  badge.appendChild(text)
  wrapper.appendChild(badge)
  return wrapper
}

// land-dots.json is a precomputed list of [lat, lng] points that fall on
// land, generated by scripts/generate-land-dots.mjs. Computing that at
// runtime via geoContains over ~16000 sphere samples takes ~10s and freezes
// the page, so only the (much cheaper) per-country highlight test runs here.
async function buildLandDots(
  highlightedCountries: string[],
  countryColor: string,
  baseColor: string
): Promise<DotPoint[]> {
  const { geoContains } = await import("d3-geo")

  const countryTopology = worldCountries as unknown as Topology
  const countryFeatures = feature(
    countryTopology,
    countryTopology.objects.countries as GeometryCollection
  ).features
  const highlightSet = new Set(highlightedCountries)
  const highlightedFeatures = countryFeatures.filter((f) =>
    highlightSet.has((f as GeoJSON.Feature).properties?.name)
  )

  return (landDots as [number, number][]).map(([lat, lng]) => {
    const isHighlighted = highlightedFeatures.some((f) => geoContains(f, [lng, lat]))
    return { lat, lng, color: isHighlighted ? countryColor : baseColor, radius: LAND_DOT_RADIUS }
  })
}

export function GlobeLive({
  offices = defaultOffices,
  highlightedCountries = defaultHighlightedCountries,
  countryColor = "#AA182C",
  baseColor = "#d8d8d8",
  className = "",
}: GlobeLiveProps) {
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!containerRef.current) return
    const el = containerRef.current
    let world: GlobeInstance | undefined
    let ro: ResizeObserver | undefined
    let cancelled = false

    Promise.all([
      import("globe.gl"),
      buildLandDots(highlightedCountries, countryColor, baseColor),
    ]).then(([{ default: Globe }, coloredLandDots]) => {
      if (cancelled) return

      const officeDots: DotPoint[] = offices.map((o) => ({
        lat: o.location[0],
        lng: o.location[1],
        color: countryColor,
        radius: OFFICE_DOT_RADIUS,
      }))

      world = new Globe(el)
        .backgroundColor("rgba(0,0,0,0)")
        .showAtmosphere(false)
        .pointsData([...coloredLandDots, ...officeDots])
        .pointLat((d) => (d as DotPoint).lat)
        .pointLng((d) => (d as DotPoint).lng)
        .pointColor((d) => (d as DotPoint).color)
        .pointRadius((d) => (d as DotPoint).radius)
        .pointAltitude(0.005)
        .pointResolution(4)
        .pointsMerge(true)
        .htmlElementsData(offices)
        .htmlLat((d) => (d as OfficeMarker).location[0])
        .htmlLng((d) => (d as OfficeMarker).location[1])
        .htmlAltitude(0.02)
        .htmlElement((d) => buildOfficeBadge(d as OfficeMarker, countryColor))

      const globeMaterial = world.globeMaterial() as { color?: { set: (c: string) => void } }
      globeMaterial.color?.set("#ffffff")

      world.controls().autoRotate = true
      world.controls().autoRotateSpeed = 0.6
      world.controls().enableZoom = false

      const resize = () => {
        const size = el.offsetWidth
        if (size > 0) world?.width(size).height(size)
      }
      resize()
      ro = new ResizeObserver(resize)
      ro.observe(el)
    })

    return () => {
      cancelled = true
      ro?.disconnect()
      world?._destructor()
    }
  }, [offices, highlightedCountries, countryColor, baseColor])

  return <div ref={containerRef} className={`relative aspect-square select-none ${className}`} />
}
